import cv2 as cv

read_flags = {
    "UNCHANGED": cv.IMREAD_UNCHANGED,
    "GRAYSCALE": cv.IMREAD_GRAYSCALE,
    "COLOR":  cv.IMREAD_COLOR,
    "ANYDEPTH": cv.IMREAD_ANYDEPTH,
    "ANYCOLOR": cv.IMREAD_ANYCOLOR,
    "LOAD_GDAL": cv.IMREAD_LOAD_GDAL,
    "REDUCED_GRAYSCALE_2": cv.IMREAD_REDUCED_GRAYSCALE_2,
    "REDUCED_COLOR_2": cv.IMREAD_REDUCED_COLOR_2,
    "REDUCED_GRAYSCALE_4": cv.IMREAD_REDUCED_GRAYSCALE_4,
    "REDUCED_COLOR_4": cv.IMREAD_REDUCED_COLOR_4,
    "REDUCED_GRAYSCALE_8": cv.IMREAD_REDUCED_GRAYSCALE_8,
    "REDUCED_COLOR_8": cv.IMREAD_REDUCED_COLOR_8,
    "IGNORE_ORIENTATION": cv.IMREAD_IGNORE_ORIENTATION
}